// <auto-generated />
using AlCopilot.DrinkCatalog.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AlCopilot.DrinkCatalog.Data.Migrations
{
    [DbContext(typeof(DrinkCatalogDbContext))]
    [Migration("20260428090415_AddIngredientGroups")]
    partial class AddIngredientGroups
    {
    }
}
