// <auto-generated />
using System;
using AlCopilot.Recommendation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlCopilot.Recommendation.Data.Migrations
{
    [DbContext(typeof(RecommendationDbContext))]
    partial class RecommendationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recommendation")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("FeedbackCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackRating")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawMessageJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("ChatSessionId", "NativeMessageId")
                        .IsUnique();

                    b.HasIndex("ChatSessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("AgentMessages", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.AgentMessageDiagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentMessageId");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("AgentMessageDiagnostics", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("InputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OutputTokenCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ReasoningTokenCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("AgentRuns", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentSessionStateJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatSessions", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecommendationTurnGroups", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DrinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RecommendationTurnGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationTurnGroupId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecommendationTurnItems", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItemMatchedSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecommendationTurnItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationTurnItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecommendationTurnItemMatchedSignals", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItemMissingIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RecommendationTurnItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationTurnItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecommendationTurnItemMissingIngredients", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItemRecipeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("boolean");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RecommendationTurnItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationTurnItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecommendationTurnItemRecipeEntries", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Shared.Data.DomainEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DomainEventRecords", "recommendation");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.AgentMessage", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.AgentMessageDiagnostic", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.AgentMessage", null)
                        .WithMany()
                        .HasForeignKey("AgentMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.AgentRun", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnGroup", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItem", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("RecommendationTurnGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItemMatchedSignal", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItem", null)
                        .WithMany("MatchedSignals")
                        .HasForeignKey("RecommendationTurnItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItemMissingIngredient", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItem", null)
                        .WithMany("MissingIngredients")
                        .HasForeignKey("RecommendationTurnItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItemRecipeEntry", b =>
                {
                    b.HasOne("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItem", null)
                        .WithMany("RecipeEntries")
                        .HasForeignKey("RecommendationTurnItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlCopilot.Recommendation.Features.Recommendation.RecommendationTurnItem", b =>
                {
                    b.Navigation("MatchedSignals");

                    b.Navigation("MissingIngredients");

                    b.Navigation("RecipeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
